In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('properati_br_2016_11_01_properties_rent.csv.zip', compression='zip')
pd.set_option('display.max_columns', None)

In [3]:
data

,created_on,operation,property_type,place_name,place_with_parent_names,geonames_id,lat_lon,lat,lon,price,currency,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses,properati_url,description,title,image_thumbnail,location
0,2013-04-25,rent,apartment,Praia Grande,|Brasil|São Paulo|Praia Grande|,NaN,NaN,NaN,NaN,900.0,BRL,898.29,280.84,NaN,NaN,NaN,NaN,NaN,1.0,NaN,http://praia-grande-sao-paulo.properati.com.br...,"Otimo Imovel com o melhor valor da regiao, con...",Apartamento Em Praia Grande,NaN,NaN
1,2013-04-25,rent,apartment,Alphaville,|Brasil|São Paulo|Barueri|Alphaville|,NaN,NaN,NaN,NaN,3200.0,BRL,3193.99,998.56,NaN,NaN,NaN,NaN,NaN,3.0,NaN,http://alphaville-barueri.properati.com.br/q8z...,"Otimo Imovel com o melhor valor da regiao, con...",Apartamento Em Barueri,https://thumbs-cf.properati.com/0/Wjq7toq-DpwK...,NaN
2,2013-04-25,rent,house,Centro,|Brasil|São Paulo|Jundiaí|Centro|,NaN,NaN,NaN,NaN,1800.0,BRL,1796.62,561.69,NaN,NaN,NaN,NaN,NaN,2.0,NaN,http://centro-jundiai.properati.com.br/qe2_alu...,"Otimo Imovel com o melhor valor da regiao, con...",Casa Em Jundiai,NaN,NaN
3,2013-04-25,rent,apartment,Alphaville,|Brasil|São Paulo|Barueri|Alphaville|,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://alphaville-barueri.properati.com.br/s9p...,"Otimo Imovel com o melhor valor da regiao, con...",Apartamento Em Barueri,https://thumbs-cf.properati.com/0/X7PtsZjj8Vqz...,NaN
4,2013-04-25,rent,apartment,Barueri,|Brasil|São Paulo|Barueri|,NaN,NaN,NaN,NaN,1800.0,BRL,1796.62,561.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://barueri.properati.com.br/s9u_aluga-se_a...,"Otimo Imovel com o melhor valor da regiao, con...",Apartamento Em Barueri,https://thumbs-cf.properati.com/9/URn3U3gg-F6C...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97348,2016-11-01,rent,apartment,Vila Adyana,|Brasil|São Paulo|São José dos Campos|Vila Ady...,NaN,NaN,NaN,NaN,1600.0,BRL,1596.99,499.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://vila-adyana.properati.com.br/2hk0a_alug...,Apto em excelente localização com 3 dormitório...,Apto Vila AdyAna,https://thumbs-cf.properati.com/9/fO9avKeVE4nA...,NaN
97349,2016-11-01,rent,apartment,Jardim Aquárius,|Brasil|São Paulo|São José dos Campos|Jardim A...,NaN,NaN,NaN,NaN,2000.0,BRL,1996.24,624.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://jardim-aquarius.properati.com.br/2hk0b_...,"Apartamento novo com 2 dormitórios, sendo 1 su...",Apto Mobiliado Lindo Aquarius,https://thumbs-cf.properati.com/0/8vf7zRE3UU2K...,NaN
97350,2016-11-01,rent,apartment,Jardim Aquárius,|Brasil|São Paulo|São José dos Campos|Jardim A...,NaN,NaN,NaN,NaN,1900.0,BRL,1896.41,592.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://jardim-aquarius.properati.com.br/2hk0c_...,Apto novo no Jd. Aquarius ampla varanda gourme...,Lindo Apto Aquarius 2 vagas,https://thumbs-cf.properati.com/1/WGdWsXr0_NtM...,NaN
97351,2016-11-01,rent,apartment,Votorantim,|Brasil|São Paulo|Votorantim|,NaN,NaN,NaN,NaN,900.0,BRL,898.29,280.84,NaN,NaN,NaN,NaN,NaN,1.0,301.0,http://votorantim-sao-paulo.properati.com.br/2...,Apartamento novíssimo no Ed. Alpha Club: - 2 d...,Apartamento para locação no Ed. Alpha Club,https://thumbs-cf.properati.com/1/8Lgn4c8Wj4eL...,NaN
97352,2016-11-01,rent,apartment,Copacabana,|Brasil|Rio de Janeiro|Rio de Janeiro|Copacabana|,NaN,POINT(-43.188034 -22.966091),-22.966091,-43.188034,1800.0,BRL,1796.62,561.69,NaN,33.0,17.020909,54.545455,NaN,1.0,650.0,http://copacabana.properati.com.br/2hk0j_aluga...,SULMAR - Excelente apartamento em frente ao ho...,"Apartamento residencial para locação, Copacaba...",https://thumbs-cf.properati.com/0/zyBPyDLyQ7tW...,POINT(-43.188034 -22.966091)

In [6]:
data.shape

(97353, 25)

In [8]:
data.columns

Index(['created_on', 'operation', 'property_type', 'place_name',
       'place_with_parent_names', 'geonames_id', 'lat_lon', 'lat', 'lon',
       'price', 'currency', 'price_aprox_local_currency', 'price_aprox_usd',
       'surface_total_in_m2', 'surface_covered_in_m2', 'price_usd_per_m2',
       'price_per_m2', 'floor', 'rooms', 'expenses', 'properati_url',
       'description', 'title', 'image_thumbnail', 'location'],
      dtype='object')

In [5]:
data.isna().sum()

created_on                        0
operation                         0
property_type                     0
place_name                        0
place_with_parent_names           0
geonames_id                   97350
lat_lon                       51323
lat                           51323
lon                           51323
price                          5019
currency                       5020
price_aprox_local_currency     5019
price_aprox_usd                5019
surface_total_in_m2           81505
surface_covered_in_m2         21769
price_usd_per_m2              26938
price_per_m2                  26938
floor                         92068
rooms                         38590
expenses                      65580
properati_url                     0
description                       0
title                             0
image_thumbnail                5134
location                      51323
dtype: int64

In [10]:
data1 = data.dropna(axis=,inplace=False)
data1

Empty DataFrame
Columns: [created_on, operation, property_type, place_name, place_with_parent_names, geonames_id, lat_lon, lat, lon, price, currency, price_aprox_local_currency, price_aprox_usd, surface_total_in_m2, surface_covered_in_m2, price_usd_per_m2, price_per_m2, floor, rooms, expenses, properati_url, description, title, image_thumbnail, location]
Index: []